### ISSUE TITLE
Sugestão: Remover carousel

### ISSUE THREAD

**Issue by paulodiovani** [samuelreichert/feevale-hospedagem-web-2015#2]
Aquele carousel no _header_ está bem feio, além de tirar atenção do conteúdo principal, que são os planos.

Por mim tiramos ele e deixamos o mais _clean_ possível.

cc: @fabiobeneditto

**Comment by samuelreichert** [comment]
@paulodiovani @fabiobeneditto Se todos concordarem eu tiro.

**Comment by FabioBeneditto** [comment]
Não vi, mas tem meu voto para tirar.

:wq!

Fabio Beneditto
"A vida é mais bela quando vista de cima de uma motocicleta"
"A hacker does for love what anyone will do for money"
Em 30/10/2015 18:58, "Samuel Reichert" notifications@github.com escreveu:

**Comment by paulodiovani** [comment]
Fixed in #3.
